// This function was generated by ChatGPT
export const getNumDaysInCurrentMonth = () => {
  const currentDate = new Date();
  const year = currentDate.getFullYear();
  const month = currentDate.getMonth() + 1;

  const lastDayOfMonth = new Date(year, month, 0);

  return lastDayOfMonth.getDate();
};

// This function was generated by ChatGPT
export const getNumDaysInCurrentYear = () => {
  const currentYear = new Date().getFullYear();
  if (
    currentYear % 4 === 0 &&
    (currentYear % 100 !== 0 || currentYear % 400 === 0)
  ) {
    return 366; // Leap year
  } else {
    return 365; // Regular year
  }
};

// This function was generated by ChatGPT
export const daysInYearToDate = () => {
  const now = new Date();
  const startOfYear = new Date(now.getFullYear(), 0, 1);
  const timeDifference = now.getTime() - startOfYear.getTime();
  const daysElapsed = Math.floor(timeDifference / (1000 * 60 * 60 * 24));

  return daysElapsed + 1; // Adding 1 because the current day is inclusive
};
