// This function was generated by ChatGPT
export const getNumDaysInCurrentMonth = () => {
  const currentDate = new Date();
  const year = currentDate.getFullYear();
  const month = currentDate.getMonth() + 1;

  const lastDayOfMonth = new Date(year, month, 0);

  return lastDayOfMonth.getDate();
};

// This function was generated by ChatGPT
export const getNumDaysInCurrentYear = () => {
  const currentYear = new Date().getFullYear();
  if (
    currentYear % 4 === 0 &&
    (currentYear % 100 !== 0 || currentYear % 400 === 0)
  ) {
    return 366; // Leap year
  } else {
    return 365; // Regular year
  }
};

// This function was generated by ChatGPT
export const daysInYearToDate = () => {
  const now = new Date();
  const startOfYear = new Date(now.getFullYear(), 0, 1);
  const timeDifference = now.getTime() - startOfYear.getTime();
  const daysElapsed = Math.floor(timeDifference / (1000 * 60 * 60 * 24));

  return daysElapsed + 1; // Adding 1 because the current day is inclusive
};

export const getDaysUntilNextThanksgiving = () => {
  const getThanksgivingDate = (year: number) => {
    // Find the first Thursday in November and add 3 weeks to it
    let thanksgivingDate = new Date(year, 10, 1);
    while (thanksgivingDate.getDay() !== 4) {
      thanksgivingDate.setDate(thanksgivingDate.getDate() + 1);
    }
    thanksgivingDate.setDate(thanksgivingDate.getDate() + 21);
    return thanksgivingDate;
  };

  const now = new Date();
  const currentYear = now.getFullYear();

  const currentYearThanksgiving = getThanksgivingDate(currentYear);
  const nextYearThanksgiving = getThanksgivingDate(currentYear + 1);

  if (now.valueOf() - currentYearThanksgiving.valueOf() > 0) {
    // If we are past the current year's Thanksgiving, the next holiday must be next year
    return Math.floor(
      (nextYearThanksgiving.valueOf() - now.valueOf()) / 1000 / 60 / 60 / 24
    );
  }

  // The next Thanksgiving is this year
  return Math.floor(
    (currentYearThanksgiving.valueOf() - now.valueOf()) / 1000 / 60 / 60 / 24
  );
};

export const getDaysUntilNextDate = (
  month: number /* Month is 1 indexed */,
  day: number
) => {
  const now = new Date();
  const currentYear = now.getFullYear();

  const currentYearDate = new Date(currentYear, month - 1, day);
  const nextYearDate = new Date(currentYear + 1, month - 1, day);

  if (now.valueOf() - currentYearDate.valueOf() > 0) {
    // If we are past the current year's Thanksgiving, the next holiday must be next year
    return Math.floor(
      (nextYearDate.valueOf() - now.valueOf()) / 1000 / 60 / 60 / 24
    );
  }

  // The next Thanksgiving is this year
  return Math.floor(
    (currentYearDate.valueOf() - now.valueOf()) / 1000 / 60 / 60 / 24
  );
};
